[package]
name = "AquaQ"
version = "0.1.0"
edition = "2024"
default-run = "AquaQ_02"

[dependencies]

[[bin]]
name = "run_all"
path = "runAquaQ.rs"

[profile.dev]
debug = 0   # ðŸš« no debug info â†’ no .pdb files
